version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: event-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_booking
    ports:
      - "3308:3306"
    volumes:
      # This line automatically runs your init.sql when the container is created
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  node-api:
    build: .
    container_name: event-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=event_booking
    depends_on:
      mysql-db:
        condition: service_healthy